repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files #Prevent giant files from being committed.
        args: [ '--maxkb=1024' ]
      - id: check-ast #Simply check whether files parse as valid python.
      - id: check-builtin-literals #Require literal syntax when initializing empty or zero Python builtin types.
      - id: check-docstring-first #Checks for a common error of placing code before the docstring.
      - id: check-executables-have-shebangs #Checks that non-binary executables have a proper shebang.
      - id: check-json #Attempts to load all json files to verify syntax.
        exclude: "metadata/data/"
      - id: check-byte-order-marker #removes UTF-8 byte order marker
      - id: end-of-file-fixer #Makes sure files end in a newline and only a newline.
      - id: check-case-conflict #Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: check-merge-conflict #Check for files that contain merge conflict strings.
      - id: check-symlinks #Checks for symlinks which do not point to anything.
      - id: check-toml #Attempts to load all TOML files to verify syntax.
      - id: check-vcs-permalinks #Ensures that links to vcs websites are permalinks.
      - id: check-xml #Attempts to load all xml files to verify syntax.
      - id: check-yaml #Attempts to load all yaml files to verify syntax.
        args: [ --allow-multiple-documents ]
      - id: debug-statements #Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: detect-private-key #Checks for the existence of private keys.
      - id: destroyed-symlinks #Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-aws-credentials #Checks for the existence of AWS secrets that you have set up with the AWS CLI.
        args: [--allow-missing-credentials]
      - id: mixed-line-ending #Replaces or checks mixed line ending.
        args: [ '--fix=lf' ] #Forces replacing line ending by respectively LF


  - repo: https://github.com/timothycrosley/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.1"
    hooks:
      - id: flake8
        args: [ --config=.flake8 ]
        additional_dependencies: [ flake8-docstrings, flake8-annotations ]
